[.text-justify]
= Sling TG
:reproducible:
:doctype: article
:author: Herman Ciechanowiec
:email: herman@ciechanowiec.eu
:chapter-signifier:
:sectnums:
:sectnumlevels: 5
:sectanchors:
:toc: left
:toclevels: 5
:icons: font
// Docinfo is used for foldable TOC.
// -> For full usage example see https://github.com/remkop/picocli
:docinfo: shared,private
:linkcss:
:stylesdir: https://www.ciechanowiec.eu/linux_mantra/
:stylesheet: adoc-css-style.css

== Overview

_Sling TG_ is a web framework for managing https://telegram.org/[Telegram] bots. It encapsulates technical interactions with the bots so that the user of the framework can focus solely on implementing business logic for their bots.

== Details
=== Boilerplate Code and Persistence Logic

The https://core.telegram.org/bots/api[Telegram Bot API] can be complex. Using it often requires Telegram bot owners to develop a significant amount of non-business-related code, such as for bot registration and data extraction from updates. This code is often repetitive and requires substantial effort to replicate for each new bot.

Another essential aspect of Telegram bot development is persisting bot activity. The Telegram Bot API is stateless, meaning bot owners must store bot activities in an external database, requiring them to implement persistence logic from scratch.

_Sling TG_ addresses these challenges by providing abstractions that encapsulate non-business-related code, offering a standardized approach to interacting with the Telegram Bot API and managing data persistence. This way, users of _Sling TG_ need only implement their business logic and provide the required bot configurations.

=== Usage Examples
The framework's unit tests contain complete examples illustrating how to use _Sling TG_, i.a. how to configure a bot, persist updates, and send messages.

=== Maven Coordinates
_Sling TG_ coordinates in Maven Central Repository are the following:

[source, xml]
----
<dependency>
    <groupId>eu.ciechanowiec</groupId>
    <artifactId>sling.rocket.telegram</artifactId>
    <version>1.0.4</version>
</dependency>
----

=== Sling Rocket
_Sling TG_ is built on the https://github.com/ciechanowiec/sling_rocket[Sling Rocket] web framework and is designed to be used exclusively within that environment.

=== Secrets

Unit tests are executed with two real Telegram bots, and require passing the bot tokens and chat ID as system properties: `sling.firstBotToken`, `sling.secondBotToken`, and `sling.chatID`. You can set these properties as follows:

[source,bash]
....
mvn clean install \
    -Dsling.firstBotToken=HIDDEN_TOKEN \
    -Dsling.secondBotToken=HIDDEN_TOKEN \
    -Dsling.chatID=HIDDEN_CHAT_ID
....

== License
The program is subject to MIT No Attribution License

Copyright © 2024 Herman Ciechanowiec

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the 'Software'), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so.

The Software is provided 'as is', without warranty of any kind, express or implied, including but not limited to the warranties of merchantability, fitness for a particular purpose and noninfringement. In no event shall the authors or copyright holders be liable for any claim, damages or other liability, whether in an action of contract, tort or otherwise, arising from, out of or in connection with the Software or the use or other dealings in the Software.
